/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;


import vistas.VistaLogin;
import vistas.VistaMonitoreoConTabla;
import vistas.VistaSimuladorLlamada;

/**
 *
 * @author Julio Peraza
 */
public class AplicacionObligatorio extends javax.swing.JFrame {

    /**
     * Creates new form InicioAplicacion
     */
    public AplicacionObligatorio() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        itemLogin = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        itemSimuladorLlamadas = new javax.swing.JMenuItem();
        itemMonitoreo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        itemLogin.setText("Inicio");

        jMenuItem1.setText("Login");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        itemLogin.add(jMenuItem1);

        itemSimuladorLlamadas.setText("Simulador de llamadas");
        itemSimuladorLlamadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSimuladorLlamadasActionPerformed(evt);
            }
        });
        itemLogin.add(itemSimuladorLlamadas);

        itemMonitoreo.setText("Monitoreo");
        itemMonitoreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMonitoreoActionPerformed(evt);
            }
        });
        itemLogin.add(itemMonitoreo);

        jMenuBar1.add(itemLogin);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       new VistaLogin(this,false).setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void itemSimuladorLlamadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSimuladorLlamadasActionPerformed
        new VistaSimuladorLlamada(this,false).setVisible(true);
    }//GEN-LAST:event_itemSimuladorLlamadasActionPerformed

    private void itemMonitoreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMonitoreoActionPerformed
        new VistaMonitoreoConTabla(this,false).setVisible(true); 
    }//GEN-LAST:event_itemMonitoreoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu itemLogin;
    private javax.swing.JMenuItem itemMonitoreo;
    private javax.swing.JMenuItem itemSimuladorLlamadas;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}

