/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vistas;

import controlador.ControladorAplicacionTrabajadores;;
import modelo.Puesto;
import modelo.Trabajador;
import controlador.IVistaAplicacionTrabajadores;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import modelo.Puesto;
import modelo.Trabajador;
import controlador.IVistaAplicacionTrabajadores;
import javax.swing.JOptionPane;


/**
 *
 * @author Julio Peraza
 */
    public class VistaAplicacionTrabajadores extends javax.swing.JDialog implements IVistaAplicacionTrabajadores {
    private ControladorAplicacionTrabajadores controlador;
    
    
    /**
     * Creates new form VistaAplicacionParaTrabajadores
     */
    public VistaAplicacionTrabajadores(java.awt.Frame parent, boolean modal, Trabajador t, Puesto p) {
        super(parent, modal);
        initComponents();
        controlador = new ControladorAplicacionTrabajadores(t,p,this);
        mostrarDatosTrabajadorPuesto(t,p);
                
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bSalir = new javax.swing.JButton();
        labelNombreTrabajador = new javax.swing.JLabel();
        labelSectorYPuesto = new javax.swing.JLabel();
        lblLlamadasAtendidas = new javax.swing.JLabel();
        lblTiempoPromedio = new javax.swing.JLabel();
        lblLlamadaEnEspera = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaDescripcion = new javax.swing.JTextArea();
        btnFinalizarLlamada = new javax.swing.JButton();
        lblFechaDeInicio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aplicacion para trabajadores");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        labelNombreTrabajador.setText("Trabajador:");

        labelSectorYPuesto.setText("Sector | Puesto");

        lblLlamadasAtendidas.setText("Llamadas atendidas:");

        lblTiempoPromedio.setText("Tiempo promedio:");

        lblLlamadaEnEspera.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lblLlamadaEnEspera.setText("Esperando llamada...");
        lblLlamadaEnEspera.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 255), 1, true));

        lblCliente.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblCliente.setText("Cliente:");

        jLabel1.setText("Descripcion: ");

        textAreaDescripcion.setColumns(20);
        textAreaDescripcion.setRows(5);
        textAreaDescripcion.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 255)));
        jScrollPane1.setViewportView(textAreaDescripcion);

        btnFinalizarLlamada.setText("Finalizar llamada");
        btnFinalizarLlamada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarLlamadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(lblCliente))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFechaDeInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnFinalizarLlamada)
                                    .addGap(141, 141, 141)
                                    .addComponent(bSalir))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(51, 51, 51)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblLlamadaEnEspera, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(labelSectorYPuesto)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblTiempoPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelNombreTrabajador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblLlamadasAtendidas, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelNombreTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblLlamadasAtendidas, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelSectorYPuesto)
                    .addComponent(lblTiempoPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblLlamadaEnEspera)
                .addGap(22, 22, 22)
                .addComponent(lblFechaDeInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCliente)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSalir)
                    .addComponent(btnFinalizarLlamada))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
            // TODO add your handling code here:
            boolean salir = controlador.salirDeLaAplicacion();
            if (salir) {                
                dispose();
            }

    }//GEN-LAST:event_bSalirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        controlador.salirDeLaAplicacion();

        dispose();
    }//GEN-LAST:event_formWindowClosing

    private void btnFinalizarLlamadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarLlamadaActionPerformed


        controlador.finalizarLlamada();


    }//GEN-LAST:event_btnFinalizarLlamadaActionPerformed
    @Override
    public void mostrarLlamadaFinalizada(){
        
        controlador.agregarDescripcionLlamada(textAreaDescripcion.getText());
        lblLlamadaEnEspera.setText("Llamada finalizada.");
        lblLlamadasAtendidas.setText("Llamadas atendidas: " + controlador.llamadasAtendidas());
        lblTiempoPromedio.setText("Tiempo promedio: " + controlador.llamadasTiempoPromedio());
        lblFechaDeInicio.setText("");
        lblCliente.setText("Cliente: ");
        controlador.mostrarAlertLlamadaFinalizada(this);
        controlador.limpiarLlamadaActual();
        controlador.agregarSiguienteLlamada();
    }
    
    @Override
    public void mostrarMensaje(String msj){
        JOptionPane.showMessageDialog(null, msj);        
    }
    
    
    @Override
    public void mostrarDatosTrabajadorPuesto(Trabajador t, Puesto p) {
         labelNombreTrabajador.setText("Trabajador: " + t.getNombreCompleto());
         labelSectorYPuesto.setText("Sector: " + t.getSector().getNombre() +" | Puesto: Nro. #" + p.getIdPuesto());
         lblLlamadasAtendidas.setText("Llamadas atendidas: " + p.cantidadLlamadasAtendidasTrabActual());
         lblTiempoPromedio.setText("Tiempo promedio: "+ p.tiempoPromedioLlamadas() );

         
    }
    
    @Override
    public void mostrarLlamadaEnCurso(Trabajador t, Puesto p){
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss");
        
        lblLlamadaEnEspera.setText("Llamada en curso... ");
        lblCliente.setText("Cliente: " + p.getLlamadaActual().getCliente().getNombre());        
        lblFechaDeInicio.setText("Fecha de inicio: "+ sdf.format(p.getLlamadaActual().getAtendida()));
        lblLlamadasAtendidas.setText("Llamadas atendidas: " + p.cantidadLlamadasAtendidasTrabActual());
    }
    
    @Override
    public boolean confirmarSalida() {
        int i = JOptionPane.showConfirmDialog(this, "Desea salir?", "Confirmar salida", 1);
        return  i == JOptionPane.OK_OPTION;  
    }

    @Override
    public void mostrarMensajePantalla(String cadena){
        lblLlamadaEnEspera.setText(cadena);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bSalir;
    private javax.swing.JButton btnFinalizarLlamada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelNombreTrabajador;
    private javax.swing.JLabel labelSectorYPuesto;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblFechaDeInicio;
    private javax.swing.JLabel lblLlamadaEnEspera;
    private javax.swing.JLabel lblLlamadasAtendidas;
    private javax.swing.JLabel lblTiempoPromedio;
    private javax.swing.JTextArea textAreaDescripcion;
    // End of variables declaration//GEN-END:variables



    
}
